# Generated by Django 3.0.8 on 2020-09-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
